### PR TITLE
feat!: Upgrade to Fastify 5 and Node 20

### PR DESCRIPTION
**Pull request by markrzen**
BREAKING CHANGES

- Upgrade to Fastify 5.x and Node 20.x
- NOTE: Changes some error responses due to https://github.com/fastify/fastify-jwt/pull/325 upgrade.

Resolves: #366

### CODE REVIEW

**Comment by markrzen** [comment]
@simoneb Here is the follow up to yesterdays Fastify 5.x upgrade on `@nearform/fastify-jwt-jwks`.

**Comment by simoneb** [comment]
Thanks @markrzen for the PR. CI is broken presumably because it needs some secrets to be set during execution, which are not available in forks for security reasons. Are you comfortable that if we merge this, CI will be green in master?

**Comment by markrzen** [comment]
@simoneb All the other tests run successfully. That's about as confident as I can get. We could change the base to be a branch on your origin, then merge it there, so CI runs?

**Comment by simoneb** [comment]
Nah I'm good with merging to master, if anything breaks we can still follow up

**Review by simoneb — APPROVED** [review]

**Pull request merged**
